# Generated by Django 5.1.6 on 2025-03-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/default.jpg', null=True, upload_to='static/images/profiles/'),
        ),
    ]
