# Generated by Django 5.1.6 on 2025-03-14 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_adress_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User0',
        ),
    ]
