# Generated by Django 5.1.6 on 2025-03-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_user_user0'),
    ]

    operations = [
        migrations.AddField(
            model_name='user0',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
