# Generated by Django 5.1.6 on 2025-03-15 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user0_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user0',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
