# Generated by Django 5.1.6 on 2025-03-12 12:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polo',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('market_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('polo_sleeve', models.CharField(max_length=200)),
                ('polo_fit', models.CharField(max_length=200)),
                ('fabric', models.CharField(max_length=200)),
                ('ideal_for', models.CharField(max_length=200)),
                ('tshirt_type', models.CharField(choices=[('polo', 'Polo'), ('round', 'Round Neck')], default='polo', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TShirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PoloImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('polo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='LasGraphicas.polo')),
            ],
        ),
    ]
