# Generated by Django 5.1.6 on 2025-03-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('market_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('polo_sleeve', models.CharField(max_length=200)),
                ('polo_fit', models.CharField(max_length=200)),
                ('fabric', models.CharField(max_length=200)),
                ('ideal_for', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TShirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
