# Generated by Django 5.1.6 on 2025-03-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LasGraphicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polo',
            name='fabric_care',
            field=models.CharField(choices=[('dontIron', 'Do not Iron on Print/Embroidary/embellishment'), ('regular', 'Regular Machine Wash')], default='regular', max_length=50),
        ),
        migrations.AddField(
            model_name='polo',
            name='fabric_weight',
            field=models.CharField(default='250 g', max_length=50),
        ),
        migrations.AddField(
            model_name='polo',
            name='occasion',
            field=models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('sports', 'Sports'), ('party', 'Party')], default='casual', max_length=20),
        ),
        migrations.AddField(
            model_name='polo',
            name='pattern',
            field=models.CharField(choices=[('printed', 'Printed'), ('plain', 'Plain'), ('embroidary', 'Embroidary')], default='printed', max_length=50),
        ),
        migrations.AddField(
            model_name='polo',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='polo',
            name='size',
            field=models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], default='l', max_length=10),
        ),
        migrations.AlterField(
            model_name='polo',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='polo',
            name='fabric',
            field=models.CharField(choices=[('cotton', 'Bio Wash Cotton'), ('honeycomb', 'Honeycomb Cotton'), ('polyester', 'Polyester'), ('wool', 'Wool'), ('other', 'Other')], default='cotton', max_length=50),
        ),
        migrations.AlterField(
            model_name='polo',
            name='ideal_for',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('other', 'Other')], default='men', max_length=20),
        ),
        migrations.AlterField(
            model_name='polo',
            name='market_price',
            field=models.IntegerField(default=999),
        ),
        migrations.AlterField(
            model_name='polo',
            name='polo_fit',
            field=models.CharField(choices=[('loose', 'Loose Fit'), ('normal', 'Normal')], default='loose', max_length=50),
        ),
        migrations.AlterField(
            model_name='polo',
            name='polo_sleeve',
            field=models.CharField(choices=[('3/4', '3/4'), ('full', 'Full'), ('half', 'Half')], default='half', max_length=20),
        ),
        migrations.AlterField(
            model_name='polo',
            name='selling_price',
            field=models.IntegerField(default=699),
        ),
    ]
