# Generated by Django 5.1.6 on 2025-03-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LasGraphicas', '0002_polo_fabric_care_polo_fabric_weight_polo_occasion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polo',
            name='fabric',
            field=models.CharField(choices=[('Bio Wash Cotton', 'Bio Wash Cotton'), ('Honeycomb Cotton', 'Honeycomb Cotton'), ('polyester', 'Polyester'), ('wool', 'Wool'), ('other', 'Other')], default='Bio Wash Cotton', max_length=50),
        ),
        migrations.AlterField(
            model_name='polo',
            name='polo_fit',
            field=models.CharField(choices=[('Loose', 'Loose'), ('Regular', 'Regular')], default='Loose', max_length=50),
        ),
        migrations.AlterField(
            model_name='polo',
            name='polo_sleeve',
            field=models.CharField(choices=[('3/4', '3/4'), ('Full', 'Full'), ('Half', 'Half')], default='Half', max_length=20),
        ),
    ]
