# Generated by Django 5.1.6 on 2025-03-13 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LasGraphicas', '0003_alter_polo_fabric_alter_polo_polo_fit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TShirt',
        ),
    ]
