# Generated by Django 5.1.6 on 2025-03-07 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LasGraphicas', '0003_polo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polo',
            name='image',
        ),
        migrations.CreateModel(
            name='PoloImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('polo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='LasGraphicas.polo')),
            ],
        ),
    ]
