# Generated by Django 5.1.6 on 2025-03-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LasGraphicas', '0005_wishlist_delete_product_alter_polo_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='home-page', max_length=100, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='static/images/homepage')),
                ('main_heading', models.TextField(blank=True, max_length=255, null=True)),
                ('main_description', models.TextField(blank=True, max_length=500, null=True)),
                ('first_image', models.ImageField(blank=True, null=True, upload_to='static/images/homepage')),
                ('first_heading', models.TextField(blank=True, max_length=255, null=True)),
                ('first_description', models.TextField(blank=True, max_length=500, null=True)),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='static/images/homepage')),
                ('second_heading', models.TextField(blank=True, max_length=255, null=True)),
                ('second_description', models.TextField(blank=True, max_length=500, null=True)),
                ('third_image', models.ImageField(blank=True, null=True, upload_to='static/images/homepage')),
                ('third_heading', models.TextField(blank=True, max_length=255, null=True)),
                ('third_description', models.TextField(blank=True, max_length=500, null=True)),
                ('fourth_image', models.ImageField(blank=True, null=True, upload_to='static/images/homepage')),
                ('fourth_heading', models.TextField(blank=True, max_length=255, null=True)),
                ('fourth_description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
