# Generated by Django 5.1.6 on 2025-03-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LasGraphicas', '0006_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/homepage'),
        ),
    ]
