# Generated by Django 5.1.6 on 2025-03-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LasGraphicas', '0007_homepage_brand_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polo',
            options={'ordering': ['-created']},
        ),
    ]
